[project]
name = "dynamic_dependency"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.hooks.custom]
